Check for packages.config in pure C# updater.
dependabot/dependabot-core pull request #10858
Opened 2024-10-28 15:43 UTC by sebasgomez238

Last week we added functionality in the ruby code to check for a packages.config file in the same directory of each csproj. I confirmed this change correctly updates all relevant packages.config files relevant to the update #10803.

This PR adds the same functionality to the C# updater to ensure we don't regress when it is ready to be used.

2024-10-28 15:48 UTC, sebasgomez238 commented on nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
> +        var discoveredUpdatedDependencies = GetUpdatedDependencyListFromDiscovery(discoveryResult, repoDirectory);
Still need to verify this the correct variable to pass when running e2e.

2024-10-28 16:01 UTC, sebasgomez238 commented on nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
> +        var discoveredUpdatedDependencies = GetUpdatedDependencyListFromDiscovery(discoveryResult, repoDirectory);
Resolving. Based on RunWorker unit tests repoContentsPath.FullName gives me the path I want here.

2024-10-28 18:04 UTC, brettfo requested changes

2024-10-28 18:09 UTC, sebasgomez238 commented on nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core.Test/Run/UpdatedDependencyListTests.cs
> +        var updatedDependencyList = RunWorker.GetUpdatedDependencyListFromDiscovery(discovery, path_to_contents: temp.DirectoryPath);
Ah sorry, using VS Code makes me feel like I'm using python again.

2024-10-28 20:55 UTC, sebasgomez238 commented on nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
> +            var pathToPackagesConfig = Path.Join(pathToContents, "src", projectDirectory, "packages.config").NormalizePathToUnix().EnsurePrefix("/");
Reminder to remove this hard coded "src"

2024-10-31 18:32 UTC, sebasgomez238 commented on nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
> +                            .Single(d => d.Name == dependency.Name);
Still need to investigate more on whether removing this check is okay or if there is a way to check for the correct file. Will be done before completing this PR.

2024-11-05 17:34 UTC, brettfo commented on nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs
> +        lastSlash = fullRepoPath.LastIndexOf('/');
You can use `Path.GetDirectoryName()` to do this work for you.  Something like `Path.Combine(Path.GetDirectoryName(fullRepoPath), "packages.config")`

2024-11-06 17:38 UTC, brettfo approved these changes

2024-11-06 18:30 UTC, merged