Adds python 3.8.9 and 3.9.3, closes #3439
dependabot/dependabot-core pull request #3440
Opened 2021-04-04 10:54 UTC by sobolevn

2021-04-04 11:25 UTC, sobolevn commented
Looks like `pyenv` is not ready to support `3.8.9` yet:

```
        Dependabot::SharedHelpers::HelperSubprocessFailed:
         python-build: definition not found: 3.9.3

         See all available versions with `pyenv install --list'.
```

2021-04-04 11:31 UTC, sobolevn commented
Now it looks like it should do it 👍

2021-04-04 12:24 UTC, Parnassius commented on Dockerfile
> +  && cd /usr/local/.pyenv && git checkout 32ba5d5e617b7d7fb1c9b79c1c0e8f1cfe642cd1 && cd - \
Version 1.2.25 was just released
```suggestion
  && cd /usr/local/.pyenv && git checkout v1.2.25 && cd - \
```

2021-04-04 12:39 UTC, sobolevn commented on Dockerfile
> +  && cd /usr/local/.pyenv && git checkout 32ba5d5e617b7d7fb1c9b79c1c0e8f1cfe642cd1 && cd - \
Thanks!

2021-04-06 08:34 UTC, Parnassius requested changes
In the meantime python 3.9.3 was recalled due to an ABI incompatibility, and was replaced by [3.9.4](https://www.python.org/downloads/release/python-394/). Pyenv also [made a new release](https://github.com/pyenv/pyenv/releases/tag/1.2.26) to support it

2021-04-06 08:34 UTC, Parnassius commented on Dockerfile
> +  && pyenv install 3.9.3 \
```suggestion
  && cd /usr/local/.pyenv && git checkout v1.2.26 && cd - \
  && pyenv install 3.9.4 \
```

2021-04-06 08:34 UTC, Parnassius commented on Dockerfile
> +  && pyenv global 3.9.3
```suggestion
  && pyenv global 3.9.4
```

2021-04-06 08:34 UTC, Parnassius commented on python/helpers/build
> +PYENV_VERSION=3.9.3  pyenv exec pip install -r "requirements.txt"
```suggestion
PYENV_VERSION=3.9.4  pyenv exec pip install -r "requirements.txt"
```

2021-04-06 08:34 UTC, Parnassius commented on python/lib/dependabot/python/python_versions.rb
> +        3.9.3 2.7.18
```suggestion
        3.9.4 2.7.18
```

2021-04-06 08:34 UTC, Parnassius commented on python/lib/dependabot/python/python_versions.rb
> +        3.9.3 3.9.2 3.9.1 3.9.0
```suggestion
        3.9.4 3.9.2 3.9.1 3.9.0
```

2021-04-06 08:34 UTC, Parnassius commented on python/spec/dependabot/python/update_checker/pipenv_version_resolver_spec.rb
> +                to include("supported in Dependabot: 3.9.3, 3.9.2, 3.9.1")
```suggestion
                to include("supported in Dependabot: 3.9.4, 3.9.2, 3.9.1")
```

2021-04-06 12:05 UTC, jurre approved these changes
Thanks for adding this! I noticed from the PR history that adding a python version is quite painful if you're not intimately familiar wit our setup. Would you mind sticking a small note in the README explaining how to do it for the next person?

2021-04-06 12:16 UTC, sobolevn commented
Sure!

You mean this `README`? https://github.com/dependabot/dependabot-core/blob/main/python/README.md
Or the main one?

2021-04-06 12:17 UTC, jurre commented
> Sure!
> 
> You mean this `README`? https://github.com/dependabot/dependabot-core/blob/main/python/README.md
> Or the main one?

Wherever you would have hoped to find it 😄 I think the main one might be easier for visibility?

2021-04-06 12:39 UTC, sobolevn commented
It looks like `python/README.md` is more intuitive.

2021-04-06 12:54 UTC, jurre commented
Thanks @sobolevn 💛

2021-04-06 17:43 UTC, merged