npm: prevent scoped registries becoming global
dependabot/dependabot-core pull request #4061
Opened 2021-07-19 11:01 UTC by feelepxyz

Fixes a bug where all packages (public and private) are forced through a
private registry, where it's only intended to be used for scoped
packages so fails for public packages hosted on npm.

Added a check to the method that attempts to extract a global registry,
checking if credentials registry host has already been configured in
`.npmrc` as a scoped registry.

This prevents dependabot from re-writing the `.npmrc` global `registry`
with the scoped registry:

2021-07-19 12:53 UTC, brrygrdn requested changes
Change looks good to me, one question about the `foo copy` files I think might be cruft, otherwise 👍🏻

2021-07-19 12:53 UTC, brrygrdn commented on npm_and_yarn/spec/fixtures/projects/yarn/scoped_private_source_with_npmrc copy/package.json
> +{
Unintentional check-in?

2021-07-19 12:53 UTC, brrygrdn commented on npm_and_yarn/spec/fixtures/projects/yarn/scoped_private_source_with_npmrc copy/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Same as above?

2021-07-19 14:22 UTC, feelepxyz commented on npm_and_yarn/spec/fixtures/projects/yarn/scoped_private_source_with_npmrc copy/package.json
> +{
Yep good catch!

2021-07-20 08:11 UTC, jurre approved these changes
Thanks for tackling this

2021-07-20 08:12 UTC, jurre commented on npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb
> +              line.match(/:registry\s*=\s*(?<registry>\S+)/)&.named_captures&.fetch("registry")
We could maybe extract a constant for the regex here, but not blocking for review

2021-07-20 09:15 UTC, jurre approved these changes

2021-07-20 09:39 UTC, brrygrdn approved these changes

2021-07-20 11:34 UTC, merged