feat(:git): do not decline valid git@... source
dependabot/dependabot-core pull request #4490
Opened 2021-12-06 17:00 UTC by sebbrandt87

Now it will be possible to also pass the source_type(source_string) call 
with a terraform valid git@... source property being set.

The function git_source_details_from(source_string) is already prepared 
to handle this type.

2021-12-06 18:22 UTC, jurre commented
This looks good to me, cc @Nishnha wdyt?

2021-12-06 21:24 UTC, Nishnha requested changes
I did not know that we had previously excluded `git@` sources!

Nit: Can we reuse an existing test module with the `git@` protocol? Perhaps https://github.com/dependabot/dependabot-core/blob/0146d0f2572124d337563e9a667a1ffe1e579fd5/terraform/spec/fixtures/projects/git_tags_012/main.tf#L199-L210 ?

Otherwise, this looks good to me!

2021-12-06 22:46 UTC, sebbrandt87 commented
😎
The reason I initial did not want to reuse an existing test module, is that there is also an extra catch just for direct github.com sources. So I decided for now I don't want to touch that piece and instead extend the `:git` catch.

2021-12-07 16:31 UTC, Nishnha commented
Yep, that makes sense to me @sebbrandt87 
Can I request that you change the test folder name, then? 💟 

We originally used the `git_tags_0xx` folder naming scheme to test changes between Terraform 0.11 and 0.12 😅 
Maybe a more appropriate folder name would be `git_protocol`? What do you think?

2021-12-07 16:35 UTC, sebbrandt87 commented
I am doing it right now @Nishnha 👍

2021-12-07 17:29 UTC, sebbrandt87 commented
Btw @Nishnha I force pushed to keep a clean history. Hope this was okay in this case here.

2021-12-07 18:29 UTC, Nishnha approved these changes
LGTM 👍🏾 
We will merge this in and release it with our next Dependabot-Core release 😄 
If it's okay with you, we will mention you in the release notes!

2021-12-07 18:30 UTC, merged