fix typos in GitHub issue bug report template
dependabot/dependabot-core pull request #5015
Opened 2022-04-20 07:43 UTC by tyrann0us

They have been flagged by Grammarly.

2022-04-20 07:47 UTC, jurre commented
Going to let a native speaker on the team take a look at these but seems like style changes and they seem to make things _less_ clear to me

2022-04-20 07:51 UTC, tyrann0us commented
Thanks. Yes, the only actual grammar fix is
> […] to reproducing […]

to
> […] to reproduce […]

The rest are "style" changes.

2022-04-21 12:04 UTC, brrygrdn requested changes
I've added a couple of suggestions above, otherwise this seems like a sensible tidy up

2022-04-21 12:04 UTC, brrygrdn commented on .github/ISSUE_TEMPLATE/bug-report.md
> +**Manifest location and content before update**
```suggestion
**Manifest location and content before the Dependabot update**
```

👍🏻  on the before/prior to change - 'the update' seems ambiguous when I read it back so let's be specific.

2022-04-21 12:04 UTC, brrygrdn commented on .github/ISSUE_TEMPLATE/bug-report.md
> +**Images of the diff or a link to the PR, issue, or logs**
Controversial, but I am a fan of the oxford comma myself 😂

2022-04-22 13:58 UTC, merged