fix: make sure to escape requests
dependabot/dependabot-core pull request #6382
Opened 2023-01-05 12:22 UTC by jmartens

This should fix requests failing for URLs composed of parts where spaces might be possible

ref: #6381

2023-01-05 19:11 UTC, jeffwidman approved these changes
Thanks!

2023-01-05 19:12 UTC, jeffwidman commented
FYI: If you replace `ref: https://github.com/dependabot/dependabot-core/issues/6381` with `Fix https://github.com/dependabot/dependabot-core/issues/6381` or one of the magic keywords here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword then it will auto-close the linked issue when the PR is merged.

2023-01-05 22:24 UTC, jeffwidman commented
Hmm, I'm not sure myself, but will try to take a poke later tonight or tomorrow to learn enough to form an opinion.

2023-01-06 12:33 UTC, jmartens commented
Tried the following options:

```
require 'cgi'
require "erb"
include ERB::Util

str = "https://api.bitbucket.org/2.0/repositories/maastro/eclipse-plan-check/src/60b700fd84a73bdf82398426d8a9809197b3e56e/Eclipse Plan Check.sln";

puts "\nCGI.escape: " + CGI.escape(str)

puts "\nurl_encode: " + url_encode(str)

puts "\nURI::encode: " + URI::encode(str)

puts "\nERB::Util.url_encode: " + ERB::Util.url_encode(str)

puts "\nURI::Parser.new.escape: " + URI::Parser.new.escape(str)
```

with the following results:
```
require 'cgi'
require "erb"
include ERB::Util

str = "https://api.bitbucket.org/2.0/repositories/maastro/eclipse-plan-check/src/60b700fd84a73bdf82398426d8a9809197b3e56e/Eclipse Plan Check.sln";

puts "\nCGI.escape: " + CGI.escape(str)

puts "\nurl_encode: " + url_encode(str)

puts "\nURI::encode: " + URI::encode(str)

puts "\nERB::Util.url_encode: " + ERB::Util.url_encode(str)

puts "\nURI::Parser.new.escape: " + URI::Parser.new.escape(str)
```

Decided to use the latter.

2023-01-06 17:16 UTC, Nishnha requested changes

2023-01-06 17:16 UTC, Nishnha commented on common/lib/dependabot/clients/bitbucket.rb
> +          URI::Parser.new.escape(url),
Our linter suggested

```suggestion
          URI::DEFAULT_PARSER.escape(url),
```

2023-01-06 17:53 UTC, Nishnha approved these changes
Re-approving

2023-01-06 18:03 UTC, merged

2023-01-06 18:45 UTC, jmartens commented
@Nishnha I have not been able to find any reference or definition for it. Are you sure the current implementation does the correct conversion? How can we validate that easily?

2023-01-06 19:58 UTC, Nishnha commented
> @Nishnha I have not been able to find any reference or definition for it. Are you sure the current implementation does the correct conversion? How can we validate that easily?

`URI::DEFAULT_PARSER` is equivalent to `URI::Parser.new` with no opts https://github.com/ruby/ruby/blob/66bc620963407dbfd6f4e532a61018905a490aeb/lib/uri/common.rb#L23-L24