Variety of file changes related to the MIT license change
dependabot/dependabot-core pull request #9717
Opened 2024-05-13 19:09 UTC by abdulapopoola

Updating a number of files in order to reflect the MIT license change and to clean up some inconsistencies.

Resolving a number of tasks in this epic: https://github.com/github/dependabot-updates/issues/5568

2024-05-13 19:11 UTC, jakecoffman approved these changes
😎

2024-05-13 19:18 UTC, jonjanego requested changes

2024-05-13 19:18 UTC, jonjanego commented on CONTRIBUTING.md
> +By submitting a contribution, you agree that contribution is licensed to GitHub under the [MIT license](LICENSE.txt).
```suggestion
By submitting a contribution, you agree that contribution is licensed to GitHub under the [MIT license](LICENSE).
```

2024-05-13 19:26 UTC, jonjanego approved these changes

2024-05-13 19:41 UTC, jurre approved these changes

2024-05-13 19:56 UTC, Nishnha approved these changes

2024-05-13 20:00 UTC, carogalvin approved these changes

2024-05-13 20:33 UTC, merged

2024-05-13 20:55 UTC, andymckay commented
👍🏾 😎

2024-05-13 20:58 UTC, jakecoffman commented
@mattt you might enjoy this PR

2024-05-14 00:54 UTC, kurtraschke commented
The README still states "This repo provides the logic necessary for hosting your own standalone Dependabot, as long as you're [not reselling Dependabot to others](https://github.com/dependabot/dependabot-core#license)". Presumably the second clause no longer applies? (The section of the README that the link points at has been deleted...)

2024-05-14 15:58 UTC, jonjanego commented
> The README still states "This repo provides the logic necessary for hosting your own standalone Dependabot, as long as you're [not reselling Dependabot to others](https://github.com/dependabot/dependabot-core#license)". Presumably the second clause no longer applies? (The section of the README that the link points at has been deleted...)

Good eyes, thanks @kurtraschke! That was an oversight during our changes.

2026-08-14 08:34 UTC, baslabofhd777-lab reviewed
مساعدة في اتمتت العمل